# Generated by Django 5.0.3 on 2024-06-13 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=uuid.UUID('e81c034f-bd52-45b2-8cdb-e76ef131ba0b'), max_length=180),
        ),
    ]
