# Generated by Django 5.0.3 on 2024-06-13 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=uuid.UUID('b11686d6-5b4a-4f61-9e6e-6803b6e461af'), max_length=180),
        ),
    ]
