# Generated by Django 5.0.3 on 2024-06-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_video_author_alter_videolike_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribersEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
