# Generated by Django 5.0.3 on 2024-06-13 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=uuid.UUID('20bfdc71-658a-427c-8c67-86c629de62a2'), max_length=180),
        ),
    ]
