# Generated by Django 5.0.3 on 2024-06-02 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_subscribersemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=uuid.UUID('c4f21101-9d85-4dd4-8eda-9de0c42e4485'), max_length=180),
        ),
    ]
