# Generated by Django 5.0.3 on 2024-06-13 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=uuid.UUID('4345263c-dce3-45ad-ada4-7d7ff0954d17'), max_length=180),
        ),
    ]
