# Generated by Django 5.0.3 on 2024-06-25 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(default=uuid.UUID('8b8094c5-29d6-4f4a-a5d9-4c672a2daacf'), max_length=180),
        ),
    ]
