# Generated by Django 5.0.3 on 2024-06-07 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_remove_video_category_alter_video_video_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("78c2991f-1fd6-477b-8ca7-0c150abdd0eb"),
                max_length=180,
            ),
        ),
    ]
