# Generated by Django 5.0.3 on 2024-06-07 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("f4954b7d-fb45-4e6b-bc40-01baccd1bc96"),
                max_length=180,
            ),
        ),
    ]
