# Generated by Django 5.0.3 on 2024-06-08 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0012_alter_video_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="downloads",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("7d245c14-d998-4234-8057-cca0f8a4e425"),
                max_length=180,
            ),
        ),
    ]
