# Generated by Django 5.0.3 on 2024-06-08 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0013_video_downloads_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("328972a5-64d3-46e1-89c4-ea6cd05989ac"),
                max_length=180,
            ),
        ),
    ]
