# Generated by Django 5.0.3 on 2024-06-08 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0014_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("2ccf3206-eb5e-4fc9-834c-82b3336e0b85"),
                max_length=180,
            ),
        ),
    ]
