# Generated by Django 5.0.3 on 2024-06-09 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0015_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("6a544d46-800b-4ad4-b8f7-b771d52e64a6"),
                max_length=180,
            ),
        ),
    ]
