# Generated by Django 5.0.3 on 2024-06-09 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0016_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("0032a175-fbcc-4d88-833a-ad099d6005b2"),
                max_length=180,
            ),
        ),
    ]
