# Generated by Django 5.0.3 on 2024-06-09 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0017_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(
                default=uuid.UUID("2f5e679c-8a42-419e-9b6a-b7ce6457c483"),
                max_length=180,
            ),
        ),
    ]
