# Generated by Django 5.0.3 on 2024-06-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
