# Generated by Django 5.0.3 on 2024-06-07 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_avatar_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("ab90e9d6-ab67-4459-b669-7aa14774d3e7"),
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/avatar/"),
        ),
    ]
