# Generated by Django 5.0.3 on 2024-06-07 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_user_id_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("44750129-f26d-4c76-be14-dc7455d128b6"),
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/avatar/default/avatar.jpg",
                null=True,
                upload_to="users/avatar/",
            ),
        ),
    ]
