# Generated by Django 5.0.3 on 2024-06-08 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_user_id_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("7c5bb5dc-0e41-4ffa-8809-f0e24650dc2e"),
                max_length=128,
            ),
        ),
    ]
