# Generated by Django 5.0.3 on 2024-06-08 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("f5901a65-4d20-4a21-92d1-9b7e86b214bc"),
                max_length=128,
            ),
        ),
    ]
