# Generated by Django 5.0.3 on 2024-06-09 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_user_id_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("f9acca08-a255-468a-8900-35add258f604"),
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
