# Generated by Django 5.0.3 on 2024-06-09 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_user_user_id_alter_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("a1eedd70-1064-4369-a6a3-44efdd2a05c7"),
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="users/avatar/default//avatar.jpg",
                null=True,
                upload_to="users/avatar/",
            ),
        ),
    ]
